server:
    port:8001
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
spring:
  cloud:
      getway:
         mvc:
             routes[0]:
                 id: customerservice
                 predicates[0]: Path=/api//v1/customers/**
                 uri: lb://customerservice
             routes[1]:
                id: dicvoveryserver
                predicates[0]: Path=/eureka/web
                filters[0]: SetPath=/
                uri: https://localhost:8888


